### ISSUE TITLE
Deprecated selector in `atom-underscore/styles/atom-underscore.less`

### ISSUE THREAD

**Issue by affemaen** [dborstelmann/atom-underscore#1]
In `atom-underscore/styles/atom-underscore.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .tag.template.underscore.boundary` => `atom-text-editor.editor .syntax--tag.syntax--template.syntax--underscore.syntax--boundary`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by dborstelmann** [comment]
@affemaen Thanks for the notice.  Should be good now.

**Comment by dborstelmann** [comment]
https://github.com/dborstelmann/atom-underscore/pull/3
